version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: development

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      REACT_APP_BACKEND_URL: "http://localhost:3333"
